### ISSUE TITLE
menu button doesn't work on reduced screen

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#36] opened 2019-01-09 17:07 UTC
When you resize a desktop window to very narrow, the menu button does not work. It simply refreshes the main page. Occurs in Firefox and Crome but not Safari.

![screen shot 2019-01-09 at 10 31 18 am](https://user-images.githubusercontent.com/1383000/50915545-a6a59080-13fe-11e9-8bdf-0dc8db751cb2.png)

**Comment by ludstuen90** [comment] 2019-01-12 19:57
Root cause of problem:
Header image link field overlaps the menu item. If clicking on the overlapped portion, the browser interprets the click as a click on the homepage: 
![image](https://user-images.githubusercontent.com/6817579/51077881-2c3d7080-168b-11e9-933d-218cd90df1e2.png)

**Comment by ludstuen90** [comment] 2019-01-12 19:59
Solution: Use z-index to tell browser the button should take priority. 
Fixed with: https://github.com/ludstuen90/samanthasunne/pull/45

**Closed by ludstuen90** 2019-01-12 19:59 UTC
Labels: bug
